name: New Project Support Request
description: Request support for a new project.
title: "[Project Support]: "
labels: ["project support", "triage"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request support for a new project!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What type of project support are you requesting?
      description: ( Language | Package Manager ) example: ( Rust | Cargo )
      placeholder: Tell us what solution you are looking for!
      value: "ex. A project support request for Rust and Cargo."
    validations:
      required: true